### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by ufa** [asdofindia/python-telegram-bot#2]
Hello,
Your bot are working great, many thanks. But sometimes I hit the following bug:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "bot.py", line 178, in bot
    AI(group,peer,message)
  File "bot.py", line 91, in AI
    msg(group,peer,reply)
  File "bot.py", line 113, in msg
    proc.stdin.write('msg '+peer.replace(' ','_')+' '+message+'\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 33: ordinal not in range(128)

Does this have to do with charset transformation?

**Comment by asdofindia** [comment]
This has got everything to do with Python2's unicode issues.
https://docs.python.org/2/howto/unicode.html#reading-and-writing-unicode-data says how to solve this.

**Comment by ufa** [comment]
It does not work on python 3 :cry:
